### ISSUE TITLE
PWA Top Priority Roadmap

### ISSUE THREAD

**Issue by cdparra** [morozevich/dengue-chat#1]
- [ ] Arreglar la instalación como PWA
- [ ] Implementar múltiples recorridos por equipo
- [ ] Pedir nombre de usuario y contraseña al iniciar por primera vez 
- [ ] Guardar ese nombre de usuario en firebase asociado al fcmToken que se usa para notificaciones
```json
{
    "[fcmtoken]" : {
           "user" : "[nombredeusuario], 
           "enableNotifications": "true|false => default es true",
           "dengueChatAuthToken": "[authtoken que resulte de login en denguechat]"
    }
}
```
Nota: mantener siempre el último valor guardado en fcmToken
- [ ] Implementar que las notificaciones se envíen solo a los que tienen "enableNotifications" === "true"
- [ ] Completar documentación de instalación (https://github.com/topadengue/denguechat-pwa/issues/10) 
- [ ] Asegurarse que funcione el envío de notificaciones (tenemos que hacer un testeo en vivo con usuarios)
     * Averiguar porque trata de enviar a fcmTokens que no están en firebase

- [ ] Iniciar sesión en DC
- [ ] Agregar mini-foro de DengueChat que muestre últimos 5 mensajes publicados y permita publicar un mensaje al foro
- [ ] Reemplazar mapa de barrios por un mapa offline (ver como usar el KML para simplemente mostrar el mapa sin conectarse a google maps)
